version: "3.8"

# management secret key is NAB5rGwT4qOEB+6nLQawkTfCOV2eiFSjgQK8bfEdZXY=
services:
  fluence: # /ip4/127.0.0.1/tcp/9990/ws/p2p/12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK
    command: -f ed25519 -k 29Apzfedhw2Jxh94Jj4rNSmavQ1TkNe8ALYRA7bMegobwp423aLrURxLk32WtXgXHDqoSz7GAT9fQfoMhVd1e5Ww -m 12D3KooWFRgVmb1uWcmCbmJqLr8tBQghL6ysSpK2VyE2VZbaQ6wy -t 7770 -w 9990 --local
    container_name: fluence
    environment:
      RUST_BACKTRACE: full
      RUST_LOG: info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=info,libp2p_mplex=info,libp2p_identify=info,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=info
      WASM_LOG: info
    image: fluencelabs/rust-peer:latest
    ports:
      - 4001:4001   # ipfs swarm
      - 5001:5001   # ipfs rpc
      - 7770:7770   # tcp
      - 9990:9990   # ws
      - 18080:18080 # /metrics
    restart: always
    volumes:
      - fluence:/.fluence
    networks:
      - fluence

  env.json:
    restart: "no"
    # depends_on:
    #   - fluence
    image: busybox:stable
    volumes:
      - env.json:/env
    command:
      - sh
      - -c
      - |
        cat <<EOF > /env/env.json
        {
            "nodes": [
                {
                    "multiaddr": "/dns4/localhost/tcp/9990/ws/p2p/12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK",
                    "peerId": "12D3KooWHBG9oaVx4i3vi6c1rSBUm7MLBmyGmmbHoZ23pmjDCnvK"
                }
            ]
        }
        EOF

  dashboard:
    depends_on:
      - env.json
    image: fluencelabs/dashboard:latest
    volumes:
      - env.json:/dist/env
    networks:
      - fluence
    ports:
      - 8080:8080

volumes:
  fluence: null
  env.json: null

networks:
  fluence: null
