#!/usr/bin/with-contenv bash

# s6-setuidgid abc - run as a user abc (unprivileged)

# n30          - keep 30 rotated log files
# s10000000    - rotate when log reachs 10MB
# S30000000    - keep only 30 MB of rotated (and compressed) logs
# T            - prepend timestamp to each line
# !"gzip -nq9" - compresses logs on rotation
exec \
    s6-setuidgid abc s6-log n30 s10000000 S30000000 T !"gzip -nq9" /config/log/ipfs
