{
 "title": "rust-peer stats",
 "tags": [ "rust-peer" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer\"}, env)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer\", env=~\"$env\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$env status",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "env",
   "targets": [
    {
     "expr": "min_over_time(up{job=~\"fluence|rust-peer\",env=~\"$env\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connections $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "env",
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "connection_pool_connected_peers{env=~\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(connection_pool_connected_peers{env=\"$env\",instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Particles $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Particles per current time range",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connectivity_particle_send_success_total{env=\"$env\"}[$__range]))",
       "legendFormat": "sent"
      },
      {
       "expr": "sum by (env) (increase(connection_pool_received_particles_total{env=\"$env\"}[$__range]))",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Particles per day",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connectivity_particle_send_success_total{env=\"$env\"}[1d]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (increase(connection_pool_received_particles_total{env=\"$env\"}[1d]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particles per week",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connectivity_particle_send_success_total{env=\"$env\"}[7d]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (increase(connection_pool_received_particles_total{env=\"$env\"}[7d]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particles per month",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connectivity_particle_send_success_total{env=\"$env\"}[30d]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (increase(connection_pool_received_particles_total{env=\"$env\"}[30d]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particles per day (sent)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connectivity_particle_send_success_total{env=\"$env\"}[1d]) + ignoring(day_of_week) group_right count_values without() (\"day_of_week\", day_of_week(timestamp(increase(connectivity_particle_send_success_total{env=\"$env\"}[1d])))))",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Particles per day (received)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (env) (increase(connection_pool_received_particles_total{env=\"$env\"}[1d]) + ignoring(day_of_week) group_right count_values without() (\"day_of_week\", day_of_week(timestamp(increase(connection_pool_received_particles_total{env=\"$env\"}[1d])))))",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Particles per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (env) (rate(connectivity_particle_send_success_total{env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (rate(connection_pool_received_particles_total{env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particle Send Failures",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 10, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (connectivity_particle_send_failure_total{env=\"$env\"}) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Particle Send Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (env) (connectivity_particle_send_failure_total{env=\"$env\"})",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Incoming Particle Sizes",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum(rate(connection_pool_particle_sizes_bucket{env=~\"$env\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Alive Actors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "particle_executor_alive_actors{env=~\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Connection Pool Queue Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "connection_pool_particle_queue_size{env=~\"$env\"} >= 0",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Actor mailbox size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "particle_executor_total_actors_mailbox{env=~\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Interpretation time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_interpretation_time_sec_bucket{env=~\"$env\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service call time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_service_call_time_sec_bucket{env=~\"$env\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service Calls",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_success_total{env=\"$env\"})",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Service Calls per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "targets": [
      {
       "expr": "sum by (env) (rate(particle_executor_service_call_time_sec_count{env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Call Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_failure_total{env=~\"$env\"}) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Interpretations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_successes_total{env=~\"$env\"})",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Interpretations per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
     "targets": [
      {
       "expr": "sum by (env) (rate(particle_executor_interpretation_time_sec_count{env=~\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Interpretation Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_failures_total{env=~\"$env\"}) ",
       "legendFormat": "{{env}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AquaVM stats $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Single AquaVM memory max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aqua_vm_pool_vm_mem_max{env=~\"$env\"}",
       "legendFormat": "{{ instance }} max"
      }
     ]
    },
    {
     "title": "AquaVM total memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aqua_vm_pool_vm_mem_total{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "AquaVM Pool Starvation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_no_free_vm_total{env=\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Busy AquaVMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "vm" } },
     "targets": [
      {
       "expr": "aqua_vm_pool_get_vm_total{env=\"$env\"} - aqua_vm_pool_put_vm_total{env=\"$env\"} - aqua_vm_pool_no_free_vm_total{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Busy AquaVMs (misbehaves ???)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "vms" } },
     "targets": [
      {
       "expr": "aqua_vm_pool_pool_size{env=\"$env\"} - aqua_vm_pool_free_vms{env=\"$env\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "put_vm per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_put_vm_total{env=~\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "get_vm per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 118 },
     "targets": [
      {
       "expr": "irate(aqua_vm_pool_get_vm_total{env=~\"$env\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}