{
 "title": "Service metrics",
 "tags": [ "nox" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer\"}, env)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"fluence|rust-peer\",env=~\"$env\"}, instance)"
    }
   },
   {
    "name": "service_type",
    "label": "service type",
    "query": {
     "query": "label_values(services_call_success_count_total{env=~\"$env\",instance=~\"$instance\"},service_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(services_services_count{env=~\"$env\",instance=~\"$instance\"})",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Number of services by host",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance,env) (services_services_count{env=~\"$env\",instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of worker-spells by host",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance,env) (services_services_count{env=~\"$env\",instance=~\"$instance\", service_type=\"worker-spell\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of other spells by host",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance,env) (services_services_count{env=~\"$env\",instance=~\"$instance\", service_type=\"spell\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total used memory",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum (services_mem_used_total_bytes{env=~\"$env\",instance=~\"$instance\"}) by (env,instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Total used memory by service types",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(services_mem_used_total_bytes{env=~\"$env\",instance=~\"$instance\"}) by (service_type)",
       "legendFormat": "{{ service_type }} "
      }
     ]
    },
    {
     "title": "Available memory per modules, total",
     "type": "bargauge",
     "description": "Configured maximum for services.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (services_mem_max_per_module_bytes_bucket{env=~\"$env\",instance=~\"$instance\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Available memory per services, total",
     "type": "bargauge",
     "description": "Configured maximum for services.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (services_mem_max_bytes_bucket{env=~\"$env\",instance=~\"$instance\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Succeeded/failed calls",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(services_call_success_count_total{env=~\"$env\",instance=~\"$instance\"}) by (service_type)",
       "legendFormat": "success"
      },
      {
       "expr": "sum(services_call_failed_count_total{env=~\"$env\",instance=~\"$instance\"}) by (service_type)",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Created/removed/failed to create servies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum(increase(services_creation_count_total{env=~\"$env\",instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Created"
      },
      {
       "expr": "sum(increase(services_removal_count_total{env=~\"$env\"}[$__rate_interval]))",
       "legendFormat": "Removed"
      },
      {
       "expr": "sum(increase(services_creation_failure_count_total{env=~\"$env\"}[$__rate_interval]))",
       "legendFormat": "Failed to create"
      }
     ]
    },
    {
     "title": "Service creation time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(services_creation_time_msec_bucket{env=~\"$env\",instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Service removal time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "sum(increase(services_removal_time_msec_bucket{env =~ \"$env\"}[5m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service $service_type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "service_type",
   "collapsed": true,
   "panels": [
    {
     "title": "Service calls",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(services_call_success_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"}) by (service_type)",
       "legendFormat": "success"
      },
      {
       "expr": "sum(services_call_failed_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"}) by (service_type)",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Rate of service calls ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service_type) (increase(services_call_success_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"}[$__rate_interval]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by(service_type) (increase(services_call_failed_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"}[$__rate_interval]))",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Service calls total",
     "type": "bargauge",
     "description": "Percentage from total service calls",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (services_call_success_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"})\n/\nsum (services_call_success_count_total{env=~\"$env\",instance=~\"$instance\"})",
       "legendFormat": "success"
      },
      {
       "expr": "sum (services_call_failed_count_total{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"})\n/\nsum (services_call_failed_count_total{env=~\"$env\",instance=~\"$instance\"})",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Service call time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum(increase(services_call_time_msec_bucket{env=~\"$env\",instance=~\"$instance\",service_type=\"$service_type\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Average memory usage by $service_type",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum by (instance) (services_mem_used_total_bytes{env=~\"$env\",instance=~\"$instance\",service_type=\"$service_type\"}) / sum by (instance) (services_services_count{env=~\"$env\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used memory distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 81 },
     "targets": [
      {
       "expr": "sum(increase(services_mem_used_bytes_bucket{env=~\"$env\",instance=~\"$instance\",service_type=~\"$service_type\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}