{
 "title": "Fluence Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values({__name__=\"up\"},env)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values({__name__=\"up\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$env",
     "type": "status-history",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "repeat": "env",
     "targets": [
      {
       "expr": "min_over_time(up{job=\"fluence\", env=\"$env\"}[$__interval])",
       "legendFormat": "{{ hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "connection_pool_connected_peers",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(connection_pool_connected_peers) by (hostname)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Particles",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (connectivity_particle_send_success_total)",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (connection_pool_received_particles_total)",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particles per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "sum by (env) (rate(connectivity_particle_send_success_total[$__rate_interval]))",
       "legendFormat": "{{ env }} sent"
      },
      {
       "expr": "sum by (env) (rate(connection_pool_received_particles_total[$__rate_interval]))",
       "legendFormat": "{{ env }} received"
      }
     ]
    },
    {
     "title": "Particle Send Failures",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (connectivity_particle_send_failure_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Particle Send Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 11 },
     "targets": [
      {
       "expr": "sum by (env) (connectivity_particle_send_failure_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Incoming Particle Sizes",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(increase(connection_pool_particle_sizes_bucket{ env =~ \"$env\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Alive Actors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "particle_executor_alive_actors { env =~ \"$env\" }",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Connection Pool Queue Size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "connection_pool_particle_queue_size { env =~ \"$env\" } >= 0",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Actor mailbox size",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "particle_executor_total_actors_mailbox { env=~\"$env\" }",
       "legendFormat": "{{ hostname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interpretation time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_interpretation_time_sec_bucket{ env =~ \"$env\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service call time",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(particle_executor_service_call_time_sec_bucket{ env =~ \"$env\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Service Calls",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_success_total)",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Service Calls per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sum by (env) (rate(particle_executor_service_call_time_sec_count[$__rate_interval]))",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Service Calls Failures",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_failure_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Service Call Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 21 },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_service_call_failure_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Interpretations",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_successes_total)",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Interpretations per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "sum by (env) (rate(particle_executor_interpretation_time_sec_count[$__rate_interval]))",
       "legendFormat": "{{ env }}"
      }
     ]
    },
    {
     "title": "Interpretation Failures",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_failures_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    },
    {
     "title": "Interpretation Failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 29 },
     "targets": [
      {
       "expr": "sum by (env) (particle_executor_interpretation_failures_total) ",
       "legendFormat": "{{env}}"
      }
     ]
    }
   ]
  },
  { "title": "AquaVM stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "AquaVM total memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aqua_vm_pool_vm_mem_total { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "AquaVM total memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aqua_vm_pool_vm_mem_total { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }} max"
    }
   ]
  },
  {
   "title": "Single AquaVM memory max",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aqua_vm_pool_vm_mem_max { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }} max"
    }
   ]
  },
  {
   "title": "Single AquaVM memory max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aqua_vm_pool_vm_mem_max { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }} max"
    }
   ]
  },
  {
   "title": "AquaVM Pool Starvation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "irate(aqua_vm_pool_no_free_vm_total { env =~ \"$env\" }[$__rate_interval])",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Busy AquaVMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "vm" } },
   "targets": [
    {
     "expr": "aqua_vm_pool_get_vm_total { env =~ \"$env\" } - aqua_vm_pool_put_vm_total { env =~ \"$env\" } - aqua_vm_pool_no_free_vm_total { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }}"
    },
    { "legendFormat": "{{ hostname }} fail" }
   ]
  },
  {
   "title": "Busy AquaVMs (misbehaves ???)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "vms" } },
   "targets": [
    {
     "expr": "aqua_vm_pool_pool_size { env =~ \"$env\" } - aqua_vm_pool_free_vms { env =~ \"$env\" }",
     "legendFormat": "{{ hostname }}"
    }
   ]
  }
 ]
}