#!/usr/bin/with-contenv bash

# IPFS_PATH is set to /config/ipfs in Dockerfile
# ipfs config
if [ ! -d "/config/ipfs" ]; then
	# enable Private Network feature by copying swarm.key to $IPFS_HOME
	# https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks
	cp /defaults/ipfs_preshared_swarm.key /config/ipfs/swarm.key

	ipfs init
	ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
	ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "POST"]'
	ipfs config --json Addresses.API '"/ip4/0.0.0.0/tcp/5001"'
	ipfs config --json Addresses.Gateway '"/ip4/0.0.0.0/tcp/8080"'

	# remove default bootstraps
	ipfs bootstrap rm --all
fi

# permissions
chmod -R 644 /etc/logrotate.d
