services:
  peer-1:
    image: fluencelabs/rust-peer:latest
    ports:
      - 7771:7771
      - 9991:9991
    expose:
      - 18080
    labels:
      name: peer-1
      scrape: true
    command:
      - --aqua-pool-size=2
      - -t=7771
      - -w=9991
      - --external-maddrs
      - /dns4/peer-1/tcp/7771
      - /dns4/peer-1/tcp/9991/ws
      - --local
      # 12D3KooWBM3SdXWqGaawQDGQ6JprtwswEg3FWGvGhmgmMez1vRbR
      - -k=hK62afickoeP2uZbmSkAYXxxqP8ozq16VRN7qfTP719EHC5V5tjrtW57BSjUr8GvsEXmJRbtejUWyPZ2rZMyQdq

  peer-2:
    image: fluencelabs/rust-peer:latest
    ports:
      - 7772:7772
      - 9992:9992
    expose:
      - 18080
    labels:
      name: peer-2
      scrape: true
    command:
      - --aqua-pool-size=2
      - -t=7772
      - -w=9992
      - --external-maddrs
      - /dns4/peer-2/tcp/7772
      - /dns4/peer-2/tcp/9992/ws
      - --bootstraps=/dns/peer-1/tcp/7771
      # 12D3KooWQdpukY3p2DhDfUfDgphAqsGu5ZUrmQ4mcHSGrRag6gQK
      - -k=2WijTVdhVRzyZamWjqPx4V4iNMrajegNMwNa2PmvPSZV6RRpo5M2fsPWdQr22HVRubuJhhSw8BrWiGt6FPhFAuXy

  peer-3:
    image: fluencelabs/rust-peer:latest
    ports:
      - 7773:7773
      - 9993:9993
    expose:
      - 18080
    labels:
      name: peer-3
      scrape: true
    command:
      - --aqua-pool-size=2
      - -t=7773
      - -w=9993
      - --external-maddrs
      - /dns4/peer-3/tcp/7773
      - /dns4/peer-3/tcp/9993/ws
      - --bootstraps=/dns/peer-1/tcp/7771
      # 12D3KooWRT8V5awYdEZm6aAV9HWweCEbhWd7df4wehqHZXAB7yMZ
      - -k=2n2wBVanBeu2GWtvKBdrYK9DJAocgG3PrTUXMharq6TTfxqTL4sLdXL9BF23n6rsnkAY5pR9vBtx2uWYDQAiZdrX
