name: "Update nox version"

on:
  workflow_call:
    inputs:
      version:
        description: 'Contents of fluence.json file'
        required: true

jobs:
  update:
    name: "Update version"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}

      - name: Update Fluence in fluence.json to ${{ github.event.inputs.version }}
        run: echo ${{ inputs.version }} | jq > fluence/fluence.json

      - name: Commit updated fluence.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix(deps): Update Fluence to ${{ github.event.inputs.version }}'
          commit_user_name: fluencebot
          commit_user_email: devops@fluence.one
          commit_author: fluencebot <devops@fluence.one>
