name: "Update nox version"

on:
  workflow_call:
    inputs:
      content:
        description: 'Contents of fluence.json file'
        type: string
        required: true
      version:
        description: 'Version of nox'
        type: string
        required: true
    secrets:
      token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  update:
    name: "Update version"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}

      - name: Update Fluence in fluence.json to ${{ inputs.version }}
        run: |
          cat << EOH | jq > fluence/fluence.json
          ${{ inputs.content }}
          EOH

      - name: Commit updated fluence.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix(deps): Update Nox to ${{ inputs.version }}'
          commit_user_name: fluencebot
          commit_user_email: devops@fluence.one
          commit_author: fluencebot <devops@fluence.one>
